.github/workflows/gradle.yml

develop branch only process CI
main branch process CI & CD
CI/CD 조건 변경
develop branch에 PR or push 하면 CI 과정만 진행 
main에 push 할때 (다른 branch에서 PR 요청할때) CI와 CD 동작
이슈 번호 : #10 
develop branch에 push하면 다음과 같이 CI 과정만 진행됩니다.
deploy job이 보이긴 하지만 skip 되었다고 뜨면서 진행되지 않습니다.
1. 다른 branch 에서 develop에 push 했을때
2. develop branch 에서 PR을 생성했을때 ( main으로)
main에 push되면 (PR을 승인해서 merge 했을때) CI와 CD가 모두 동작합니다.
CI과정에서 error가 발생하면 CD가 진행되지 않습니다.
<br/>

[chore] update cicd condition

---

build.gradle
src/main/java/space/space_spring/config/WebConfig.java
src/main/java/space/space_spring/config/WebSocketConfig.java
src/main/java/space/space_spring/controller/TestController.java
src/main/java/space/space_spring/dto/chat/ChatTestRequest.java
src/main/java/space/space_spring/dto/chat/ChatTestResponse.java

이슈 번호 : #15 
- config > `WebConfig` 수정 : cors 설정에 web dev address인 http://localhost:3000 추가
- config > `WebSocketConfig` 추가 : 소켓 통신 설정
- dto > chat > `ChatTestReq`, `ChatTestRes` : 테스트를 위한 채팅 메세지 DTO 생성
- controller > `TestController`
- sendMsgTest : query param의 spaceChatId를 가진 채팅방으로 메시지 발행(전송)
- subscribeTest : query param의 spaceChatId를 가진 채팅방 구독(수신)
`/topic` 엔드 포인트로 특정 채팅방을 구독하여 메시지를 수신하고,
`/app` 엔드 포인트로 특정 채팅방에 메시지를 전송합니다
(제 로컬에서 web 환경 구축해서 테스트를 진행해서, 테스트 원하시는 분들은 react 코드 드리겠습니다!)
https://github.com/user-attachments/assets/a0521733-9627-408c-b4e9-e9122ccbb759
<br/>
---

feat/#15: 웹소켓 연결 api 개발

---

build.gradle
src/main/java/space/space_spring/config/S3config.java
src/main/java/space/space_spring/controller/ImageS3Controller.java
src/main/java/space/space_spring/service/S3Uploader.java
src/main/resources/application.yml

S3에 이미지를 업로드하는 기능을 추가하고 테스트 이미지를 저장할 수 있는 컨트롤러를 추가 했습니다.
이슈 번호 : #34 
S3 연결을 위한 설정 코드 추가 
- application.yml 파일 추가 
- build.gradle에 S3 의존성 추가
- S3 관련 환경변수 추가
S3 파일 업로드를 위한 클래스 투가
- S3config
- S3uploader
S3 업로드 기능 테스트 컨트롤러 추가
-ImageS3Controller
S3 업로드 테스트
form body에 key 이름을 "file"로 설정하고, 이미지를 업로드하면, S3 에 저장된 URL 주소를 응답합니다.
단, S3 관련 환경 변수를 설정해줘야 합니다.
업로드 과정에서 문제 발생 시, S3가 아니라 local에 생성된 이미지 파일이 삭제되지 않고 남아있을 수 있습니다.
이 경우, 같은 이름의 파일을 다시 업로드 하면, `"MultipartFile -> File 전환 실패"` 에러 메세지가 발생합니다.
혹시 테스트 과정 중 다른 에러가 나더라도, local에 사진 파일이 삭제 되었는지 확인해주세요.
저장된 이미지 파일을 어떻게 프론트 엔드에서 보여줄지 정해야합니다.
현재는 응답 받은 이미지 주소로 바로 접속 가능합니다.
S3 요금 제도와 서비스 구조를 고려해서 정하면 좋을 것 같아요.

Feat/#34/S3 이미지 저장소 연결

---

src/main/java/space/space_spring/config/InterceptorURL.java
src/main/java/space/space_spring/controller/UserController.java
src/main/java/space/space_spring/dao/UserSpaceDao.java
src/main/java/space/space_spring/dto/user/GetSpaceInfoForUserResponse.java
src/main/java/space/space_spring/dto/user/SpaceChoiceViewDto.java
src/main/java/space/space_spring/service/UserService.java

로그인한 유저의 jwt를 포함한 요청을 보내면, 유저가 속한 스페이스 이름 & 썸네일 정보들을 response로 보내주는 api 입니다
무한 스크롤을 구현하기 위해 request에 size, lastUserSpaceId 값을 requestParam으로 전달받고,response에 lastUserSpaceId 값을 추가하였습니다
만약, 더 이상 보여줄 스페이스 목록이 없는 경우에는 response의 lastUserSpaceId 로 -1을 넘겨주게 되어 프론트 단에서 더 이상 유저가 속한 스페이스가 없다는 것을 인지할 수 있습니다.
추후 스페이스 생성 api에서  aws s3에 직접 사진을 업로드하는 기능을 추가한 후, 저장한 사진의 url이 응답으로 잘 전달되는 지 확인해봐야할거 같습니다.
이슈 번호 : #31 
로그인 한 유저만이 보낼 수 있는 요청이므로, 인가처리를 위해 api의 요청 url 인 /user/space-choice 를 InterceptorURL 클래스에 추가하였습니다.
현재는 response로 넘겨줄 스페이스 정보 데이터가 없는 경우, 빈 껍데기를 전송합니다. 추후에 프론트 개발자 분과 상의를 통해 이런 경우 다른 방식으로 response를 넘겨야 할 가능성이 있어, 일단 서비스단에서 코드의 분기처리만 진행하였습니다
<br/>
---
* P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 …

31 스페이스 선택 view api

---

src/main/java/space/space_spring/controller/PayController.java
src/main/java/space/space_spring/controller/SpaceController.java
src/main/java/space/space_spring/controller/TestController.java
src/main/java/space/space_spring/controller/UserController.java
src/main/java/space/space_spring/dao/PayDao.java
src/main/java/space/space_spring/dto/pay/GetPayViewResponse.java
src/main/java/space/space_spring/dto/pay/PayReceiveInfoDto.java
src/main/java/space/space_spring/dto/pay/PayRequestInfoDto.java
src/main/java/space/space_spring/entity/PayRequest.java
src/main/java/space/space_spring/entity/PayRequestTarget.java
src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java
src/main/java/space/space_spring/service/PayService.java
src/main/java/space/space_spring/service/UserService.java
src/main/java/space/space_spring/util/space/SpaceUtils.java
src/main/java/space/space_spring/util/user/UserUtils.java
src/test/java/space/space_spring/service/PayServiceTest.java

메뉴의 정산 홈으로 들어왔을때 필요한 데이터들을 프론트단으로 보내주는 api 입니다
유저가 해당 스페이스 내에서 요청한 정산 중, 현재 진행중인 정산 리스트 정보와
유저가 해당 스페이스 내에서 요청받은 정산 중, 현재 진행중인 정산 리스트 정보를 response 값으로 보내줍니다.
서비스단의 코드를 junit5와 Mockito 를 이용하여 테스트하였고, 테스트가 잘 작동되는것을 확인했습니다.
다만, 레포지토리단의 코드는 아직 테스트를 해보지 않았습니다.
추후에 정산을 직접 생성하는 api를 개발한 후, 실제 db에 데이터가 잘 들어가는지 확인하거나, 레포지토리단의 테스트코드도 추가해보겠습니다.
이슈 번호 : #37 
- 정산 관련 컨트롤러, 서비스, 레포지토리 클래스 생성 (계층 구조 생성)
- request로 넘어오는 spaceId에 해당하는 스페이스 엔티티를 찾기위해 SpaceUtils 클래스 정의
- jwt로 확인할 수 있는 유저가 request로 넘어오는 스페이스에 속하는 유저인지를 확인하기 위해 UserSpaceUtils의 검증 로직을 컨트롤러에서 수행 
-> 이 검증 로직은 유저가 스페이스 내에서 수행하는 작업을 위한 모든 api 에서 필요할 것 같습니다.
- 서비스 단 코드를 테스트하기 위한 PayServiceTest 클래스 생성
현재 정산 관련 서비스 단의 코드가 조금 지저분합니다.
추후에 리펙토링을 할 계획인데, 코드 리펙토링에 대한 의견있으면 리뷰 남겨주시면 감사하겠습니다
<br/>
---
* P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 …

37 정산 view api

---

src/main/java/space/space_spring/controller/PayController.java
src/main/java/space/space_spring/dao/PayDao.java
src/main/java/space/space_spring/dto/pay/GetRequestPayViewResponse.java
src/main/java/space/space_spring/service/PayService.java
src/test/java/space/space_spring/service/PayServiceTest.java

내가 요청한 정산 view를 구성하는 데이터를 반환하기 위한 api를 개발하였습니다
유저가 요청한 정산 중 현재 진행중인 정산과 완료된 정산을 구분하여 response dto 를 구성하였고, 이에 대한 간단한 테스트 코드를 작성하여 테스트가 통과하는 것을 확인하였습니다
이슈 번호 : #43 
기존 PayService 에 유저가 요청한 정산에 대한 정보와, 유저가 요청받은 정산에 대한 정보를 받아오는 코드가 있었습니다. 
이 코드에 각각 정산의 상태가 현재 진행중인지 완료된 정산인지를 구분하여 정산 정보를 return 할 수 있도록 boolean isComplete 파라미터를 추가하였습니다
PatServiceTest 클래스에서 테스트 코드를 참고하시면 됩니다.
현재 유저가 같은 스페이스 내의 다른 유저에게 요청한 정산이 현재 진행중인 경우, 완료된 경우에 대한 테스트 코드를 작성해두었습니다.
<br/>
---

feat/#43/내가 요청한 정산 리스트 api 개발

---

src/main/java/space/space_spring/controller/PayController.java
src/main/java/space/space_spring/controller/SpaceController.java
src/main/java/space/space_spring/dao/PayDao.java
src/main/java/space/space_spring/dao/SpaceDao.java
src/main/java/space/space_spring/dto/pay/GetRequestPayViewResponse.java
src/main/java/space/space_spring/dto/space/PostSpaceCreateRequest.java
src/main/java/space/space_spring/dto/space/PostSpaceCreateResponse.java
src/main/java/space/space_spring/service/PayService.java
src/main/java/space/space_spring/service/SpaceService.java
src/main/java/space/space_spring/validator/ValidFile.java
src/main/java/space/space_spring/validator/ValidFileValidator.java
src/test/java/space/space_spring/service/PayServiceTest.java

기존 스페이스 생성 api는 썸네일 이미지의 url을 임의의 문자열로 지정해 db에 저장하였는데,
프론트단에서 직접 이미지 파일을 전달받아 aws s3에 저장하고 return 받은 url을 db에 저장하도록 코드를 수정하였습니다.
이슈 번호 : #44 
- json 형태가 아니라 form 데이터 형식으로 request dto를 전달받으므로, controller단에서 dto를 전달받을때 @ModelAttribute 어노테이션을 이용하도록 코드를 수정하였습니다.
- request dto로 받을 MultipartFile 타입 이미지 파일의 validation을 위해 ConstraintValidator 를 구현한 ValidFileValidator 를 추가하고, 이를 이용하기 위해 @ValidFile 어노테이션을 생성하였습니다.
postman으로 폼 데이터 형식의 request body를 구성하여 요청을 날리면, 응답으로 url 주소를 반환하도록 하였습니다.
이를 클릭하시면 요청보낼시에 입력한 이미지 파일을 확인할 수 있습니다.
<br/>
---

Refactor/#44/스페이스 생성 api 에서 실제 이미지 데이터 저장

---

build.gradle
src/main/java/space/space_spring/config/QueryDslConfig.java
src/main/java/space/space_spring/config/WebConfig.java
src/main/java/space/space_spring/controller/ChatRoomController.java
src/main/java/space/space_spring/dao/chat/ChatRoomDao.java
src/main/java/space/space_spring/dao/chat/UserChatRoomDao.java
src/main/java/space/space_spring/dao/chat/custom/ChatRoomDaoCustom.java
src/main/java/space/space_spring/dao/chat/custom/ChatRoomDaoImpl.java
src/main/java/space/space_spring/dto/chat/ChatRoomResponse.java
src/main/java/space/space_spring/dto/chat/CreateChatRoomRequest.java
src/main/java/space/space_spring/dto/chat/CreateChatRoomResponse.java
src/main/java/space/space_spring/dto/chat/ReadChatRoomResponse.java
src/main/java/space/space_spring/entity/ChatRoom.java
src/main/java/space/space_spring/entity/UserChatRoom.java
src/main/java/space/space_spring/exception/ChatException.java
src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java
src/main/java/space/space_spring/service/ChatRoomService.java
src/main/java/space/space_spring/util/userSpace/MemoryUserSpaceUtils.java
src/main/java/space/space_spring/util/userSpace/UserSpaceUtils.java

이슈 번호 : #29 
채팅방 조회, 생성 및 참여 API 개발
- `QueryDSL`을 통한 쿼리 작성
- JpaRepository 인터페이스를 상속 및 커스텀하여 dao 생성
- 채팅방 생성 시 사진 및 권한 처리
채팅방 입장은 프론트에서 처리하는 부분이라
관련 자료들 노션 API 명세서에 첨부해놓았습니다
헤더에 `Authorization: Bearer {jwt}` 추가하고, API 명세서에 맞게 request 요청 시
다음과 같은 알맞은 response가 옵니다 (회원가입 후 스페이스 가입해야 테스트 가능)
<br/>
---

feat/#29: 채팅방 api 개발

---

src/main/java/space/space_spring/controller/SpaceController.java
src/main/java/space/space_spring/dao/SpaceDao.java
src/main/java/space/space_spring/dao/UserSpaceDao.java
src/main/java/space/space_spring/dto/space/GetSpaceJoinDto.java
src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java
src/main/java/space/space_spring/service/SpaceService.java
src/main/java/space/space_spring/util/userSpace/MemoryUserSpaceUtils.java
src/main/java/space/space_spring/util/userSpace/UserSpaceUtils.java

스페이스 가입 view 를 위한 데이터를 response에 담아 보내주는 api 개발
이슈 번호 : #67 
jwt에 담긴 userId와 pathVariable 로 얻을 수 있는 spaceId로 해당 유저가 이미 스페이스에 가입되어 있는 유저인지를 검증하기 위한 코드를 컨트롤러단에 구성하였습니다.
현재는 이미 스페이스에 가입된 유저일 경우, 기존의 exception 과 동일하게 500 에러가 response로 전송됩니다
상준님이 개발하신 exception handler가 develop 브랜치에 머지되면, 이슈 생성 후 예외처리의 리펙토링을 진행하겠습니다
유저가 이미 스페이스에 가입되어 있는 경우, 예외처리를 통해 response로 4xx 예외를 보내는 방법과 response 에 해당 유저가 스페이스에 가입되어 있는 지의 여부를 나타내는 필드를 추가하는 방법 중 전자가 낫다는 판단하에 개발을 진행하였습니다.
컨트롤러 단에서 검증 로직을 통해 유저가 이미 스페이스에 가입되어 있는 경우, 굳이 스페이스 가입 view 를 위해 db 를 방문하여 데이터를 얻어오는 후작업을 할 필요가 없다고 판단했기 때문입니다.
혹시 다른 의견 있으시면 리뷰 남겨주세요!!
postman을 이용하여 유저가 스페이스에 가입되어 있지 않은 경우, 이미 가입된 경우의 결과를 확인하였습니다
리펙토링 시에 테스트 코드를 추가해보겠습니다
<br/>
---
* …

Feat/#67/스페이스 가입 view api

---

src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java
src/main/java/space/space_spring/service/S3Uploader.java

download -> memory
이슈 번호 : #79 
이미지 업로드 과정 중 `MultiPartFile`을 `File`로 변환하는 과정에서 이미지가 잠시 server 파일에 저장이 되는데, 이 과정에서 EC2에서 파일 쓰기 권한이 없어 발생한 오류 입니다.
이미지 변환 과정을 서버 파일에 저장하는 것이 아니라, 메모리에서 변환 과정을 수행합니다.
`S3UpLoader` 에서 upload 내부 함수만 수정했습니다.
local에서 확인 한번 해주시고 
진짜 되는지는 배포 되는 것을 확인해 봐야 할 것 같습니다.
---

[fix] 이미지 업로드 버그 수정 

---

src/main/java/space/space_spring/config/filter/RequestCachingFilter.java
src/main/java/space/space_spring/exceptionHandler/BaseExceptionControllerAdvice.java
src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java

- 이슈 번호 : #97 
request JSON 형식에 문제가 생겼을 경우 발생하는 HttpMessageNotReadableException 처리를 추가했습니다.
해당 예외 발생시 error 코드와 request body에 무엇이 담겨 있었는지 함께 응답합니다.
- RequestCaching Fliter를 사용해서 Request body의 정보를 캐싱합니다.
- HttpNotReadableException 함수를 추가해 에러를 처리합니다.
---

HttpMessageNotReadable 예외 처리

---

src/main/java/space/space_spring/controller/SpaceController.java

userSpace 인터셉터에 space/{spaceId} 로 시작하는 모든 url이 등록되어 있어 스페이스 가입 요청 보낼 시에 오류 발생
-> 해결
이슈 번호 : #111 
<br/>
---

fix : userSpace 인터셉터 적용시키지 않아야 할 url 추가

---

src/main/java/space/space_spring/dto/chat/response/ChatRoomResponse.java
src/main/java/space/space_spring/service/ChatRoomService.java

Hotfix: lastMsg 예외처리 및 타입 변경

---

src/main/java/space/space_spring/controller/OAuthController.java
src/main/java/space/space_spring/controller/UserController.java
src/main/java/space/space_spring/dto/oAuth/OAuthLoginResponse.java
src/main/java/space/space_spring/dto/user/PostLoginDto.java
src/main/java/space/space_spring/service/UserService.java

로컬 로그인, 소셜 로그인 시 response로 success msg 대신 userId 값을 보내주도록 수정
이슈 번호 : #123 
<br/>
---

Hotfix/#123/로그인 성공시 userid return

---

src/main/java/space/space_spring/controller/VoiceRoomController.java
src/main/java/space/space_spring/dao/UserDao.java
src/main/java/space/space_spring/dao/UserSpaceDao.java
src/main/java/space/space_spring/dao/VoiceRoomDao.java
src/main/java/space/space_spring/dto/VoiceRoom/GetVoiceRoomList.java
src/main/java/space/space_spring/dto/VoiceRoom/RoomDto.java
src/main/java/space/space_spring/service/VoiceRoomService.java

- #100 
voiceRoom에서 정보 관련 저장 관련 코드를 리팩토링했습니다.
- livekit room name을 `roomName+#roomId`로 관리하던 방식을 `roomId`로 수정 했습니다. 이제 room의 이름을 수정하더라도, 같은 room으로 인식합니다.
- 참가자 profile image를 `response`와 liveKit Token `metadata`에 저장합니다. 백엔드 API, livekit API 로도 참가자의 프로필 이미지를 받아 올 수 있습니다.
- voiceRoom API에서 반환하던 userName을 userSpaceName으로 전부 변경했습니다. 해당 userSpaceDao 함수 또한 추가 하였습니다.
기존 방식으로 liveKit 참가 후, space-Profile 수정, voiceRoom 이름 수정 API를 사용해도, 정상 동작합니다.
단, 서버 API는 정보를 수정해도 일관성을 유지 하지만, LiveKit Token 정보는 중간에 수정 불가능합니다. 
LiveKit API로 받아온 정보는 수정해도 바뀌지 않습니다.
---

[Refactoring] voice room 데이터 관련 리팩토링

---

src/main/java/space/space_spring/controller/ChatRoomController.java
src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java
src/main/java/space/space_spring/service/ChatRoomService.java
src/main/java/space/space_spring/service/UserChatRoomService.java

- resolved #117 
이슈에 기재한 설명 참고 부탁드립니다
LocalDateTime 처리하는 부분에서 기준을 seoul로 맞추는 걸 누락한 부분이 있더라구요
다른 분들도 담당 도메인에서 한 번 체크해주시면 좋을 것 같습니다
<br/>
---

Hotfix/#117: lastUpdate 반환값 및 시간대 기준 위치 수정

---

src/main/java/space/space_spring/controller/ChatRoomController.java
src/main/java/space/space_spring/controller/ChattingController.java
src/main/java/space/space_spring/service/ChatRoomService.java
src/main/java/space/space_spring/service/UserChatRoomService.java

- resolved #127
socket disconnect 시에 세션에 저장된 userId와 chatRoomId를 통해, 유저가 채팅방을 떠난 시간을 저장하는 방식에서
유저가 채팅방을 떠날 때마다 http 요청을 보내면 서버에서 시간을 저장하는 로직으로 변경했습니다
비정상적인 disconnect가 발생한 경우에는 세션에 userId와 chatRoomId가 저장되어있지 않는 경우도 있는 것 같아서
해당 경우엔 userId로 user를 찾지 못하므로 불필요한 서버 오류가 많아지는 것 같아서 좀 더 확실한 방식을 선택했습니다
좋은 의견 있으시면 남겨주세요
<br/>
---

Hotfix/#127: 안읽은 메시지 버그 수정

---

src/main/java/space/space_spring/config/ThreadPoolConfig.java
src/main/java/space/space_spring/controller/LiveKitController.java
src/main/java/space/space_spring/controller/VoiceRoomController.java
src/main/java/space/space_spring/dto/VoiceRoom/RoomDto.java
src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java
src/main/java/space/space_spring/service/VoiceRoomService.java
src/test/java/space/space_spring/concurrency/completableFutureTest.java

- #96 
기존 getRoomList API는 voiceRoom list를 처리하는 과정에서 LiveKit API를 호출합니다.
이때 요청/응답 과정이 각 Room에 대해서 발생해서 getRoomList API 응답 속도가 느립니다.(특히 참가자 정보를 포함한 요청)
이를 멀티 스레드를 사용해 병렬 처리하여 속도를 개선했습니다.
- **기존 함수에 병렬 처리가 적용된 `getVoiceRoomInfoConcurrency` 함수를 추가했습니다.**
- **CompletableFuture 를 사용해서 멀티 쓰레드를 구현**
- **ThreadPoolConfig를 사용해 ThreadPool 관리**
- "/con/2" URL을 사용해서 기존 함수도 접근가능 (비상용)
-  `VOICEROOM_NOT_IN_SPACE` 에러 메세지 수정
-  CompletableFuture Test : Computable 객체를 알아보기 위한 코드들
배포 후에 VoiceRoom 사용량이 많은 상황에서 검증을 해봐야합니다
솔직히 안정성에 있어서 자신이 없습니다.
voiceRoom 20개
참가자가 포함된 voiceRoom 10개 
_기존 getRoomList API ( 참가자 정보 포함)_
_병렬 처리가 적용된 getRoomList API ( 참가자 정보 포함)_
기존 API는 room의 개수( 참가자가 존재하는 room )가 늘어날 수록 비례해서 응답시간이 증가 했습니다.
현재 병렬처리가 적용된 API는 기존 API에 비해 **약 3배** 향상된 성능을 보입니다. (위 경우에서는)
사용자들이 늘어나고, 동시 접속 중인 …

Feat/#96/voice room livekit api 병렬 처리 

---

.github/workflows/gradle.yml

- 이슈 번호 : #149 
application.yml 파일 주입 방식을 base64 암호화 방식에서 일반 파일 주입 방식으로 변경
RDS를 퍼블릭 IPv4에서 서브넷 내부방 방식으로 전환
- application.yml을 base64로 암호화해서 주입하지 않아도 됩니다.
- RDS가 전환 되었습니다. 기존 데이터가 초기화 됩니다.
- 외부에서 DB 접근이 불가능합니다.
CI/CD gitHub Action flow를 요구사항대로 변경하지 못했습니다.
1. 이중 CI 문제를 해결하기 위해 on.pull request.main을 삭제했으나, 2중 CI는 해결했지만, CI가 아예 진행되지 않고, 이전 Push CI 정보를 그대로 사용하는 것을 확인했습니다. 안정성을 위해서 기존 방식을 유지하기로 했습니다.
develop->main 으로 PR을 생성 할 시 CI action과정이 2번 표기됩니다.(실제로는 1번)
2. [chore/**] branch를 devlop에 merge(push)시에만 deploy action이 진행되는 것으로 설정 하려 했으나, gitHub Action에서 push시에 source branch 추적 기능을 제공해 주지 않아 구현이 복잡합니다. 안정성을 위해 기존 방법을 유지합니다.
"chore/"로 시작하는 브랜치를 "develop"에 PR을 생성하는 시점에 바로 deploy가 진행됩니다.
---
* …

Chore : RDS 전환, CD application.yml 주입 수정

---

src/main/java/space/space_spring/config/SecurityConfig.java
src/main/java/space/space_spring/entity/User.java
src/main/java/space/space_spring/service/UserService.java

- 이슈 번호 : #147 
사용자의 비밀번호를 암호화
회원가입 로그인에 적용
**BCryptPasswordEncoder 사용**
- SecurityConfig 수정
- endcoding 과정 회원가입에 적용
- 로그인에도 적용
- validatePassword 함수 수정
- User.passMatch 함수 삭제
해당 코드를 수정하게 되면 DB를 초기화 해야하기 때문에 유심히 봐주세요.
이 PR은 추후 RDB 관련 cd 과정을 수정하면 merge 하겠습니다. 
<br/>
---

Feat/#147/ 비밀번호 암호화

---

src/main/java/space/space_spring/controller/ChatRoomController.java
src/main/java/space/space_spring/dao/chat/ChatRoomDao.java
src/main/java/space/space_spring/dto/chat/request/CreateChatRoomRequest.java
src/main/java/space/space_spring/dto/chat/request/JoinChatRoomRequest.java
src/main/java/space/space_spring/entity/ChatRoom.java
src/main/java/space/space_spring/entity/UserChatRoom.java
src/main/java/space/space_spring/entity/document/ChatMessage.java
src/main/java/space/space_spring/service/ChatRoomService.java
src/main/java/space/space_spring/service/ChattingService.java
src/test/java/space/space_spring/controller/ChatRoomControllerTest.java
src/test/java/space/space_spring/repository/ChatRoomDaoTest.java
src/test/java/space/space_spring/repository/UserChatRoomDaoTest.java
src/test/java/space/space_spring/service/ChatRoomServiceTest.java

- resolved #145 
repository, service, controller 단에서 ChatRoom 도메인에 대한 테스트 코드 추가
- repository단 `@DataJpaTest` : 인메모리 h2 db로 테스트
- service단 `Mockito` : mock 객체를 통해 필요한 의존성 주입
- controller단 `@WebMvcTest` : 컨트롤러단 단위 테스트를 위해 프로젝트의 모든 빈을 등록하는 `@SpringBootTest` 대신 사용
실패 테스트가 필요한 부분들은 다른 브랜치에서 진행할 예정입니다.
컨트롤러단에서 interceptor를 통과하기 위해 `JwtLoginAuthInterceptor`, `UserSpaceValidationInterceptor`의 모킹 객체를, ArguementResolver의 반환값을 사용하기 위해 `JwtLoginAuthHandlerArgumentResolver`, `UserSpaceIdHandlerArgumentResolver`, `UserSpaceAuthHandlerArgumentResolver`의 모킹 객체를 추가했습니다.
<br/>
---

Feat/#145: 채팅방 테스트 코드 추가

---

src/main/java/space/space_spring/domain/board/Board.java
src/main/java/space/space_spring/domain/space/Space.java
src/main/java/space/space_spring/domain/spaceMember/SpaceMember.java
src/main/java/space/space_spring/domain/user/User.java

이슈 번호 : #178 
User, Space, SpaceMember JPA 엔티티 생성하였습니다.
필드 네이밍을 erd와 다르게 작성해보았습니다.
이렇게 discordSpaceId, discordUserId 보다는 그냥 discordId 로 통일하는거 어떨까 싶어서 엔티티의 필드명을 discordId 로 설정해놓았습니다.
혹시 다른 의견 있으시면 리뷰남겨주세엽
<br/>
---

feat : User, SpaceMember, Space 엔티티 생성

---

build.gradle
src/main/java/space/space_spring/domain/discord/adapter/in/discord/SlashCommandEventListener.java
src/main/java/space/space_spring/domain/discord/adapter/in/discord/TestTextCommandEventListener.java
src/main/java/space/space_spring/global/config/JDA/JDAConfig.java
src/main/java/space/space_spring/global/config/JDA/SlashCommandRegistrar.java
src/main/resources/application.yml

이슈 번호 : #185 
JDA를 spring 에서 사용할 수 있도록 시험 코드를 짜봤습니다.
JDA config : JDA 핵심 인스턴트 생성. 앞으로 다른 discord 관련 클래스들은 이 jda를 주입 받아 사용하게 됩니다.
discord.adapter.in.discord.~~EventListener : 디스코드 이벤트를 감지하는 클래스 입니다. inputController 처럼 사용합니다.
파일 구조에 대한 의견이 듣고 싶습니다.
그리고 디스코드가 다른 도메인들과 관련이 많은 만큼, 앞으로 어떤 디렉토리 구조가 좋을지 의견 듣고 싶습니다.
현재는 이 PR에서 처럼 Domian.discord안에 전부 넣을 생각입니다.
<br/>
---

Feat/#185/jda config bean 등록

---

src/main/java/space/space_spring/domain/discord/adapter/in/discord/TestTextCommandEventListener.java
src/main/java/space/space_spring/domain/space/SpaceMapper.java
src/main/java/space/space_spring/domain/space/adapter/in/discord/CreateSpaceEventListener.java
src/main/java/space/space_spring/domain/space/adapter/out/persistence/SpacePersistenceAdapter.java
src/main/java/space/space_spring/domain/space/adapter/out/persistence/SpringDataSpace.java
src/main/java/space/space_spring/domain/space/application/port/in/CreateSpaceCommand.java
src/main/java/space/space_spring/domain/space/application/port/in/CreateSpaceUseCase.java
src/main/java/space/space_spring/domain/space/application/port/out/CreateSpacePort.java
src/main/java/space/space_spring/domain/space/application/port/out/LoadSpacePort.java
src/main/java/space/space_spring/domain/space/application/service/CreateSpaceService.java
src/main/java/space/space_spring/domain/space/domain/Space.java
src/main/java/space/space_spring/domain/space/domain/SpaceJpaEntity.java
src/main/java/space/space_spring/domain/spaceMember/SpaceMember.java
src/main/java/space/space_spring/domain/spaceMember/SpaceMemberJpaEntity.java
src/main/java/space/space_spring/domain/spaceMember/SpaceMemberMapper.java
src/main/java/space/space_spring/domain/spaceMember/SpaceMemberPersistenceAdapter.java
src/main/java/space/space_spring/global/common/response/status/BaseExceptionResponseStatus.java
src/main/java/space/space_spring/global/config/JDA/SlashCommandRegistrar.java
src/test/java/space/space_spring/domain/pay/application/service/CreatePayServiceTest.java

discord guild를 space로 생성하는 flow
- #190 
1. discord slash command 혹은 text command(임시)를 사용해 길드 등록(`init-space`)
2. 해당 길드를 space로 생성
3. 생성된 space id를 반환
domian.space에 클린 아키텍쳐 적용하여 필요한 adapter, application, domain을 추가 하였습니다.
pay domain을 따라서 구현 해보았습니다. 
아키텍쳐 관련, 코드 관련 피드백 부탁드립니다.
추가적으로 "이미 등록된 space 확인"하는 flow가 현재 `CreateSpaceUsecase`가 `null`을 반환하는 것으로 판단됩니다.
더 좋은 코드 추천 부탁드립니다.
(따로 `checkUsecase`를 만들지 않고, controller에서 adapter를 호출하는 것을 피하기 위해서 이렇게 설계 했습니다) 
<br/>
---

[Feat] create space flow

---

build.gradle
src/main/java/space/space_spring/domain/event/adapter/in/web/createEvent/CreateEventController.java
src/main/java/space/space_spring/domain/event/adapter/in/web/joinEvent/JoinEventController.java
src/main/java/space/space_spring/domain/event/adapter/in/web/readEvent/ReadEventController.java
src/main/java/space/space_spring/global/config/SwaggerConfig.java
src/main/java/space/space_spring/global/config/interceptorURL/JwtLoginInterceptorURL.java

- resolved #240 
- swagger 의존성 추가 (v2.6.0)
- Event 도메인에 swagger 적용
**`{서버주소}/swagger-ui/index.html`** 경로로 접속하시면 됩니다. (로컬에서 확인하려면 localhost:8080/swagger-ui/index.html)
- 꼭 오른쪽 상단 `Authorize`로 토큰 입력한 후에 요청 보내야 합니다!
근데 지금은 토큰 임의로 발급받기도 까다롭고, `JwtInerceptorURL`에 등록돼있는 `/space` 패턴의 API가 없어서.. 전 임의로 url 추가 + 만료된 토큰으로 테스트해봤습니다.
- `Authorize` 후 요청 보낸 결과 
<br/>
---

Feat/#240: Swagger 추가

---

src/main/java/space/space_spring/domain/authorization/jwt/model/JwtLoginProvider.java
src/main/java/space/space_spring/domain/user/adapter/out/persistence/RefreshTokenRepository.java
src/main/java/space/space_spring/domain/user/application/service/DiscordOauthService.java
src/main/java/space/space_spring/domain/user/application/service/TokenService.java
src/main/java/space/space_spring/global/argumentResolver/jwtLogin/JwtAuthorizationArgumentResolver.java
src/main/java/space/space_spring/global/argumentResolver/jwtLogin/JwtSpaceId.java
src/main/java/space/space_spring/global/argumentResolver/jwtLogin/JwtSpaceIdArgumentResolver.java
src/main/java/space/space_spring/global/common/response/status/BaseExceptionResponseStatus.java
src/main/java/space/space_spring/global/config/WebConfig.java
src/main/java/space/space_spring/global/interceptor/jwtLogin/JwtAuthInterceptor.java
src/test/java/space/space_spring/domain/user/application/service/DiscordOauthServiceTest.java
src/test/java/space/space_spring/domain/user/application/service/TokenServiceTest.java

- resolved #238 
- access token 페이로드에 `spaceId` 추가 + interceptor에서 URL과의 id 비교 및 검증 + `@JwtSpaceId` 커스텀 어노테이션 생성
- refresh token 페이로드 `userId`로 변경
- refresh token 저장 시 Redis 자료구조 변경
로직에 문제가 있는지 한 번 봐주시면 좋을 것 같습니다.
<br/>
---

Feat/#238: jwt 토큰 페이로드 수정

---

src/main/java/space/space_spring/domain/post/adapter/out/persistence/like/LikeJpaEntity.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/like/LikeMapper.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/like/LikePersistenceAdapter.java
src/main/java/space/space_spring/domain/post/application/service/ReadPostDetailService.java
src/main/java/space/space_spring/domain/post/domain/Like.java

기존 좋아요 개수 세는 로직은 Like 테이블에서 좋아요 대상의 postBaseId를 가지고 jpql의 count 메서드를 활용합니다
그런데 좋아요 개수를 세고자하는 postBase가 아직 좋아요를 못받은 경우, Like 테이블에 해당 데이터가 없기 때문에, adapter에서 반환받은 Map에 get메서드를 적용해서 NullPointerException 이 발생한 것이었습니다
-> getOrDefault 메서드로 수정 (@arkchive 님 코드 참고했습니다!)
이슈 번호 : #329 
로컬 서버에서 확인해봤습니다!
<br/>
---

fix : 게시글 상세 조회시 좋아요 개수 수정

---

src/main/java/space/space_spring/domain/post/adapter/in/web/createPost/RequestOfCreatePost.java
src/main/java/space/space_spring/domain/post/adapter/in/web/updatePost/RequestOfUpdatePost.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/SubscriptionPersistenceAdapter.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/SubscriptionRepository.java
src/main/java/space/space_spring/domain/post/application/port/out/LoadSubscriptionPort.java
src/main/java/space/space_spring/domain/post/application/service/ReadBoardListService.java

게시판 목록 조회 시, duplicate key 에러 발생
이슈 번호 : #334
- boardId를 기준으로 태그 매핑 시, 단일 태그 값이 아닌 List<Tag>로 변경
- 태그가 없는 보드 조회 처리
<br/>
---

Fix/#334/게시판 목록 조회 오류

---

src/main/java/space/space_spring/domain/event/adapter/in/web/readEvent/EventInfoResponse.java
src/main/java/space/space_spring/domain/event/adapter/in/web/readEvent/ReadEventController.java
src/main/java/space/space_spring/domain/event/adapter/in/web/readEvent/ReadEventInfoResponse.java
src/main/java/space/space_spring/domain/event/adapter/in/web/readEvent/ReadEventsResponse.java
src/main/java/space/space_spring/domain/event/application/port/in/ReadEventUseCase.java
src/main/java/space/space_spring/domain/event/application/port/in/ResultOfEventPreviewInfo.java
src/main/java/space/space_spring/domain/event/application/service/ReadEventService.java
src/main/java/space/space_spring/domain/event/domain/EventParticipants.java
src/test/java/space/space_spring/domain/event/application/service/ReadEventServiceTest.java

행사 전체 조회 api 에 각 행사마다 총 참여 인원수를 response에 추가
프론트 측에서 행사 전체 조회 api에 각 행사마다의 총 인원수를 요청하여서 제가 코드를 좀 건드렸습니다!
@hyunn522 확인해주시고 이상없으면 내일 오전 중으로 머지 & 배포 부탁드립니다! 
(짜주신 테스트코드가 컴파일 에러가 나서 일단 주석처리 해놨습니다,,)
이슈 번호 : #345
<br/>
---

refactor : 행사 총 인원수 조회 기능 추가

---

src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CreateChannel/MoveCurrentChannelMessageButtonProcessor.java
src/main/java/space/space_spring/domain/discord/adapter/in/discord/DiscordMessageMapper.java
src/main/java/space/space_spring/domain/discord/application/port/in/discord/MessageInputFromDiscordCommand.java
src/main/java/space/space_spring/domain/discord/application/service/MessageInputFromDiscordService.java
src/main/java/space/space_spring/domain/post/application/port/in/createComment/CreateCommentCommand.java
src/main/java/space/space_spring/domain/post/application/port/in/createPost/CreatePostFromDiscordCommand.java
src/main/java/space/space_spring/domain/post/application/port/in/updatePost/UpdatePostFromDiscordCommand.java

디스코드에서 생성된 메세지/댓글에 대해 디스코드 생성 시간을 주입해줍니다.
- 이슈 번호 : #266
- 게시물/댓글 생성 시 생성시간 주입
- 이전 게시물 옮기기 기능에도 적용
- null point exception 해결
- 메세지 수정의 경우 따로 처리하지 않음
<br/>
---

Feat : 디스코드 생성 게시물에 생성 시간 주입

---

src/main/java/space/space_spring/domain/post/adapter/out/persistence/comment/CommentQueryAdapter.java
src/main/java/space/space_spring/domain/post/application/port/in/createComment/CreateCommentCommand.java
src/main/java/space/space_spring/domain/post/application/port/out/comment/AnonymousCommentCreatorView.java
src/main/java/space/space_spring/domain/post/application/port/out/comment/CommentCreatorQueryPort.java
src/main/java/space/space_spring/domain/post/application/service/CreateCommentService.java
src/main/java/space/space_spring/domain/post/application/service/strategy/AnonymousCommentProcessingStrategy.java

1. 스페이스 웹에서 익명 댓글 생성 시, 디스코드로 보내는 익명 댓글 작성자 닉네임 만드는 로직 수정
2. 게시글 상세 조회 시, 게시글 작성자가 익명 댓글을 단 경우 댓글 작성자의 닉네임을 "게시글 작성자" 로 보이도록 수정
이슈 번호 : #364 
<스페이스 웹에서의 익명 댓글 생성 api 수정>
1. CreateCommentService 에서 CommentCreatorQueryPort 을 호출하여 해당 게시글에 달린 익명 댓글들의 댓글 작성자 정보 전부 로드
2. 서비스 클래스에서 현재 익명 댓글 작성자에게 적절한 닉네임 부여 (ex. 익명 스페이서 n)
3. 이때 현재 익명 댓글 작성자가 게시글 작성자와 동일인물일 경우, 닉네임을 "게시글 작성자" 로 부여
4. 이 정보들을 CreateCommentInDiscordUseCase 로 전송 
<게시글 상세 조회 api 수정>
기존 코드에서는 익명 댓글 작성자가 해당 게시글의 작성자와 동일 인물임에도 "익명 스페이서 n" 으로 닉네임을 부여하였음
1. 위의 경우 "게시글 작성자"로 익명 댓글 작성자의 닉네임을 수정
2. 1의 요구사항을 충족하면서 다른 익명 댓글 작성자의 닉네임이 "익명 스페이서 1", "익명 스페이서 2" ,, 이런식으로 빠짐없이 순차적으로 부여되도록 AnonymousCommentProcessingStrategy 로직 수정
@drbug2000 CreateCommentCommand 의 createdAt, lastModifiedAt 의 값이 builder의 인자로 주어지지않는 경우 null 값을 가지게끔 코드를 수정했습니다.
이렇게 수정해도 …

Fix/#364/스페이스에서의 익명 댓글 생성

---

src/main/java/space/space_spring/domain/spaceMember/adapter/in/ReadAllSpaceMemberController.java
src/main/java/space/space_spring/domain/spaceMember/adapter/in/ResponseOfReadAllSpaceMember.java
src/main/java/space/space_spring/domain/spaceMember/adapter/out/persistence/SpaceMemberQueryAdapter.java
src/main/java/space/space_spring/domain/spaceMember/application/port/in/ReadSpaceMemberUseCase.java
src/main/java/space/space_spring/domain/spaceMember/application/port/out/query/SpaceMemberDetail.java
src/main/java/space/space_spring/domain/spaceMember/application/port/out/query/SpaceMemberQueryPort.java
src/main/java/space/space_spring/domain/spaceMember/application/service/ReadSpaceMemberService.java

특정 스페이스에 속하는 전체 멤버를 조회하는 api 개발
이슈 번호 : #369 
단순 조회여서 QueryPort가 반환하는 DTO인 SpaceMemberDetail 에 service, controller 모두 의존하도록 코드를 구현했습니다.
어차피 response 값이 변경될 경우 api 전체를 수정해야 하니까 하나의 model에 api의 모든 코드가 의존해도 괜찮지 않나 싶어서 이렇게 구현했습니다.
나름 CQRS 패턴으로 조회 로직을 구현했다고 봐주시면 될 듯 합니다.
로컬 서버에서 포스트맨을 사용해 테스트 해봤습니당
<br/>
---

feat : 스페이스 전체 멤버 조회 api 개발

---

src/main/java/space/space_spring/domain/post/adapter/in/web/readPostList/ReadPostListController.java
src/main/java/space/space_spring/domain/post/adapter/in/web/readPostList/ResponseOfReadPostList.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/PostPersistenceAdapter.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/SpringDataPostRepository.java
src/main/java/space/space_spring/domain/post/application/port/in/readPostList/ListOfPostSummary.java
src/main/java/space/space_spring/domain/post/application/port/in/readPostList/ReadPostListUseCase.java
src/main/java/space/space_spring/domain/post/application/port/out/LoadPostPort.java
src/main/java/space/space_spring/domain/post/application/service/ReadPostListService.java

이슈 번호 : #357
게시글 리스트 조회 시, 무한 페이징 로직 추가
Pageable 객체로 page, size 정보를 받아옵니다. page default값은 0, size default 값은 20입니다.
응답에 현재 페이지, 페이지당 개수, 전체 게시글 수, 전체 페이지 수, 마지막 페이지 여부를 포함하여 페이징 정보를 추가했습니다.
로컬 테스트 완료했습니다
<br/>
---

Feat/#357/게시판 페이징 처리

---

src/main/java/space/space_spring/domain/discord/adapter/in/discord/MessageUpdateEventListener.java

포럼 게시물 수정이 댓글 수정으로 처리 되던 오류를 수정하였습니다
- 이슈 번호 : #405
포럼 게시물을 수정하면, comment 수정 flow를 호출하는 오류를 수정하였습니다
<br/>
---

[fix] 디스코드 포럼 게시물 수정 버그 수정 

---

src/main/java/space/space_spring/domain/event/adapter/out/persistence/EventParticipantPersistenceAdapter.java
src/main/java/space/space_spring/domain/event/adapter/out/persistence/custom/EventParticipantRepositoryCustom.java
src/main/java/space/space_spring/domain/event/adapter/out/persistence/custom/EventParticipantRepositoryImpl.java
src/main/java/space/space_spring/domain/event/application/service/ReadEventParticipantService.java
src/main/java/space/space_spring/domain/home/adapter/in/web/ReadHomeResponse.java
src/main/java/space/space_spring/domain/home/application/service/ReadHomeService.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/custom/PostRepositoryImpl.java
src/main/java/space/space_spring/domain/spaceMember/adapter/out/persistence/SpaceMemberPersistenceAdapter.java
src/main/java/space/space_spring/domain/spaceMember/adapter/out/persistence/custom/SpaceMemberRepositoryCustom.java
src/main/java/space/space_spring/domain/spaceMember/adapter/out/persistence/custom/SpaceMemberRepositoryImpl.java
src/main/java/space/space_spring/domain/spaceMember/application/port/out/LoadSpaceMemberPort.java

- resolved #400 
- 홈 조회 시 구독한 게시판 중 태그가 없는 경우에 대해 최신 게시글 미리보기 구현
- 행사 참여자 조회 시 최신순 정렬 이슈 해결 : 참여자를 최신순으로 불러오는 것은 잘 동작하고 있었으나, **최신순으로 불러온 참여자들의 space member 정보를 불러오는 과정에서 최신순이 적용되지 않고 있었습니다.** 따라서 space member의 adapter에 파라미터로 넘긴 id 리스트의 순서대로 space member를 불러오는 메소드를 추가했습니다.
- 홈 조회 테스트
- 행사 참여자 조회
<br/>
---

Fix/#400: 행사 참여자 조회 및 홈 조회 미리보기 이슈

---

src/main/java/space/space_spring/domain/event/adapter/out/persistence/EventParticipantMapper.java
src/main/java/space/space_spring/domain/event/adapter/out/persistence/EventParticipantPersistenceAdapter.java
src/main/java/space/space_spring/domain/event/adapter/out/persistence/EventParticipantRepository.java
src/main/java/space/space_spring/domain/event/adapter/out/persistence/custom/EventParticipantRepositoryCustom.java
src/main/java/space/space_spring/domain/event/adapter/out/persistence/custom/EventParticipantRepositoryImpl.java
src/main/java/space/space_spring/domain/event/application/port/out/LoadEventParticipantPort.java
src/main/java/space/space_spring/domain/event/application/port/out/UpdateEventParticipantPort.java
src/main/java/space/space_spring/domain/event/application/service/ModifyEventService.java
src/main/java/space/space_spring/domain/event/domain/EventParticipant.java
src/main/java/space/space_spring/domain/event/domain/EventParticipants.java
src/test/java/space/space_spring/domain/event/application/service/JoinEventServiceTest.java

- resolved #401 
행사 참여자 추가 및 삭제 플로우에서 `추가 -> 삭제 -> 재추가 -> 재삭제 ` 엣지 케이스에 대한 처리를 추가했습니다.
스웨거에서 잘 동작하는 것 확인했습니다.
<br/>
---

Fix/#401: 행사 참여자 status 설정

---

src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/PayComplete/PayCompleteButtonProcessor.java
src/main/java/space/space_spring/domain/pay/application/service/CompletePayService.java
src/main/java/space/space_spring/global/common/response/status/BaseExceptionResponseStatus.java

resolved : #408 
- 이미 송금 완료된 정산 요청에 대해 정산 완료 처리 api 요청이 들어올 경우 HttpStatus.BAD_REQUEST exception을 throw 하도록 서비스 클래스 코드 수정
- @drbug2000 상준님 디스코드에서 정산 완료 버튼 처리하는 로직에 exception catch 할 경우 "이미 완료 처리된 정산입니다." 와 같은 적당한 메시지를 띄워주시면 감사하겠습니다!
<br/>
---

refactor : 이미 송금 완료한 정산에 대해 api 요청이 올 경우 Exception throw

---

src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/PayComplete/PayCompleteButtonProcessor.java

resolved : #408 
@drbug2000 님이 디스코드에서 메시지 띄우는 코드 추가해주셨습니다.
-> 로컬 서버 실행 & 스웨거로 정산 완료 처리한 정산 요청에 대해서 디스코드에서 정산 완료 버튼을 누를 경우, 위 화면처럼 보입니다
<br/>
---

Feat : 이미 완료한 정산에 대해 디스코드에서 "정산 완료" 버튼 누르는 경우, 메시지 띄우는 기능 추가

---

src/main/java/space/space_spring/domain/home/application/service/ReadHomeService.java

홈 조회 시 공지사항 게시판이 없을 때 null을 반환하던 기존 코드에서 빈 리스트를 반환하는 것으로 수정
<br/>
---

Hotfix: 공지사항이 없을 때 빈 리스트 반환

---

src/main/java/space/space_spring/domain/pay/application/service/ReadPayRequestListService.java
src/test/java/space/space_spring/domain/pay/application/service/ReadPayRequestListServiceTest.java

resolved : #428 
<ReadPayRequestListService 코드 수정>
- 완료된 정산을 구분하는 로직 수정
- 기존 로직 : 정산 대상의 총 인원 수 == 돈 낸 사람 수 && 정산 요청 시 총 금액 == 정산 대상들이 낸 돈의 합
- 수정된 로직 : 정산 대상의 총 인원 수 == 돈 낸 사람 수
-> 기존 로직에서는 1/n 정산에서 발생할 수 있는 나머지 금액(ex 10000원을 3명이서 정산시 1원 나머지 금액 발생) 이 비어서, exception을 throw 하고 있었습니다
<br/>
---

Hotfix/#428/완료된 정산 구분 로직

---

src/main/java/space/space_spring/domain/home/adapter/in/web/NoticeSummary.java
src/main/java/space/space_spring/domain/home/adapter/in/web/SubscriptionSummary.java
src/main/java/space/space_spring/domain/home/application/service/ReadHomeService.java

- 홈에서 공지사항 게시판 조회 시 게시물 내용이 아닌 제목 반환
- 홈에서 구독한 게시판 조회 시 boardTitle -> postTitle 네이밍 변환
<br/>
---

Hotfix: 홈 조회 시 게시물 제목 반환

---

src/main/java/space/space_spring/domain/discord/application/service/CreatePostInDiscordService.java
src/main/java/space/space_spring/domain/home/adapter/in/web/SubscriptionSummary.java
src/main/java/space/space_spring/domain/home/application/service/ReadHomeService.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/custom/PostRepositoryImpl.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/tag/TagPersistenceAdapter.java
src/main/java/space/space_spring/domain/post/application/port/out/LoadTagPort.java
src/main/java/space/space_spring/domain/post/application/service/UpdatePostService.java

- resolved #443 
- 하나의 게시판에 태그가 여러 개가 있는 경우에 대한 처리 추가
- 게시판 아이디 + 태그 아이디로 게시물 조회 시, 해당 게시물의 태그 정보 포함하여 조회
- 구독한 게시판 조회 시 태그 아이디 추가
로컬에서 테스트 완료했습니다.
<br/>
---

Fix/#443: 태그 조회 수정

---

src/main/java/space/space_spring/domain/discord/adapter/in/discord/TitleAndContentParser.java

- 이슈 번호 : #439
- 첫줄이 everyone 일 시 제목으로 사용하지 않음
- 첫줄에 everyone 포함일때 everyone 제거하고 제목으로 사용
<br/>
---

[feat] `@everyone` 이 첫줄 이어도 title로 사용하지 않습니다. 

---

src/main/java/space/space_spring/domain/discord/adapter/in/discord/MessageUpdateEventListener.java

add "return"
분기 코드 문제로 추후 다른 디자인 패턴으로 수정하는 것이 좋아 보임
- 이슈 번호 : #445 
분기 처리에서 오류가 났네요
사소한 실수로 코드 수정이 많아져서 죄송합니다
<br/>
---

[fix] 디스코드 댓글 수정 문제 해결

---

src/main/java/space/space_spring/domain/post/adapter/in/web/readPostDetail/ResponseOfReadPostDetail.java
src/main/java/space/space_spring/domain/post/adapter/in/web/readPostList/ReadPostListController.java
src/main/java/space/space_spring/domain/post/adapter/in/web/readPostList/ResponseOfPostSummary.java
src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/PostQueryAdapter.java
src/main/java/space/space_spring/domain/post/application/port/in/readPostDetail/ResultOfReadPostDetail.java
src/main/java/space/space_spring/domain/post/application/port/in/readPostList/PostSummary.java
src/main/java/space/space_spring/domain/post/application/port/in/readPostList/ReadPostListUseCase.java
src/main/java/space/space_spring/domain/post/application/port/out/post/PostDetailView.java
src/main/java/space/space_spring/domain/post/application/service/ReadPostDetailService.java
src/main/java/space/space_spring/domain/post/application/service/ReadPostListService.java

resolved : #447 
1. 게시글 상세조회 api ("/space/{spaceId}/board/{boardId}/post/{postId}") 의 response에 요청 보내는 유저가 해당 게시글의 작성자인지를 알려주는 정보 추가
2. 게시글 리스트 조회 api ("/space/{spaceId}/board/{boardId}/post") 의 response에 요청 보내는 유저가 해당 게시글의 작성자인지를 알려주는 정보 추가
<로컬 테스트 해보다가 알게된 사실>
현재 S3 upload 시에 업로드 할 수있는 파일 확장자를 `AllowedImageFileExtensions.java` enum 파일에 명시해 둔 상황
그런데 제가 HEIC 이미지 파일을 첨부파일로 해서 게시글 생성 요청을 보내니, 디스코드에 제대로 보이지 않습니다
-> 이런식으로 미리보기가 안됨 (링크 클릭하면 사진이 현재 디바이스에 다운로드 되고, 저장된 사진을 클릭하면 보이긴 함)
-> 위 사진은 jpeg 파일임 -> 미리보기 잘됨
개인적인 추측으로는 heic 파일이 용량이 커서 그런가? 싶긴한데 정확한 이유를 잘 모르겠네여. (구글링 해봐도 잘 안나오네여)
혹시 관련해서 아는 내용 있으시면 리뷰 남겨주시면 감사하겠습니다
-> 변경사항 1  로컬 테스트 결과
-> 변경사항 2 로컬 테스트 결과
로컬로는 전부 제가 글 생성하고 제가 확인하는 거여서 isPostOwner 값이 전부 true긴 합니다. dev로 배포 후 한번 확인이 필요하긴 합니다.
<br/>
---
* P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 …

Refactor/#447/게시글 상세 조회 response 추가

---

src/main/java/space/space_spring/domain/home/adapter/in/web/NoticeSummary.java
src/main/java/space/space_spring/domain/home/application/service/ReadHomeService.java

- resolved #450 
홈 조회 응답에 공지사항 게시판의 boardId 추가 (공지사항 게시판의 경우 태그는 해당이 없기 때문에 따로 추가 x)
<br/>
---

Feat/#450: 홈 조회 시 공지사항 게시판 아이디 추가
