KUIT-Space/KUIT_Space_BackEnd

- src/main/java/space/space_spring/Controller/TestController.java
이슈 번호 : #번호
webhook 연결 테스트용 pr 입니닷
<br/>
---
> feat 서버 webhook 연결 완료

- .github/workflows/gradle.yml
> [chore] fix gradle.yml

- .github/workflows/gradle.yml
gradle.,yml에 application.yml path가 추가 안되어 있는 오류 수정했습니다.
> [chore] add gradle.yml resource path

- .github/workflows/gradle.yml
- .gitignore
- src/main/resources/application.yml
add ignore application-dev
add "deploy" branch work CD
fix set application file process
다시 배포 환경 설정
1. "deploy" branch에 PR을 요청할 시, deploy job이 실행 됩니다.
- ci/cd 환경 수정 시 PR을 2번 승인 받아야 EC2에 배포가 잘 이루어지는지 확인 할 수 있는 문제가 있었습니다.
- 배포 확인용 "deploy" branch를 생성해 이 브랜치에 PR을 보내면, 배포가 이루어 지도록 설정했습니다.
2. gitignore에 application-dev.yml 추가 
- 앞으로는 배포용 application.yml 파일 내용 전체가 base64 방식으로 encoding 되어 입력되게 됩니다. 
- 따라서 배포용 application 파일인 -dev.yml을 ignore로 설정했습니다.
- 따라서 현재 파일에 있는 application.yml 배포 과정에서 쓰이는 않습니다._ (아예 내용이 새로 쓰임) 
3.  gradle.yml deploy 과정 수정
- git secret에서 base64로 인코딩된 application.yml 파일을 가져와 디코딩한 후 appliction.yml로 설정합니다. 
이슈 번호 : #11 
**앞으로 application.yml 파일 관리** 
- **application-dev는 CI/CD 담당자만 관리하면 되므로 신경 쓰지 않아도 됩니다.**
- **application.yml에 추가해야 할 환경 변수나 속성이 있으면 CI/CD 담당자한테 말하면 됩니다.**
- …
> Chore/#11/applicationyml 파일 수정 환경 변수 설정

- .github/workflows/gradle.yml
- .gitignore
- src/main/resources/application.yml
add ignore application-dev
add "deploy" branch work CD
fix set application file process
다시 배포 환경 설정
1. "deploy" branch에 PR을 요청할 시, deploy job이 실행 됩니다.
- ci/cd 환경 수정 시 PR을 2번 승인 받아야 EC2에 배포가 잘 이루어지는지 확인 할 수 있는 문제가 있었습니다.
- 배포 확인용 "deploy" branch를 생성해 이 브랜치에 PR을 보내면, 배포가 이루어 지도록 설정했습니다.
2. gitignore에 application-dev.yml 추가 
- 앞으로는 배포용 application.yml 파일 내용 전체가 base64 방식으로 encoding 되어 입력되게 됩니다. 
- 따라서 배포용 application 파일인 -dev.yml을 ignore로 설정했습니다.
- 따라서 현재 파일에 있는 application.yml 배포 과정에서 쓰이는 않습니다._ (아예 내용이 새로 쓰임) 
3.  gradle.yml deploy 과정 수정
- git secret에서 base64로 인코딩된 application.yml 파일을 가져와 디코딩한 후 appliction.yml로 설정합니다. 
이슈 번호 : #11 
**앞으로 application.yml 파일 관리** 
- **application-dev는 CI/CD 담당자만 관리하면 되므로 신경 쓰지 않아도 됩니다.**
- **application.yml에 추가해야 할 환경 변수나 속성이 있으면 CI/CD 담당자한테 말하면 됩니다.**
- …
> Chore/#10/git action 진행 조건 변경

- src/main/java/space/space_spring/controller/ChatRoomController.java
- src/main/java/space/space_spring/dao/chat/ChatRoomDao.java
- src/main/java/space/space_spring/dao/chat/UserChatRoomDao.java
- src/main/java/space/space_spring/dto/chat/request/JoinChatRoomRequest.java
- src/main/java/space/space_spring/dto/chat/response/ChatSuccessResponse.java
- src/main/java/space/space_spring/dto/chat/response/ReadChatRoomMemberResponse.java
- src/main/java/space/space_spring/entity/BaseEntity.java
- src/main/java/space/space_spring/entity/ChatRoom.java
- src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java
- src/main/java/space/space_spring/service/ChatRoomService.java
- resolved #69
- 채팅방 이름 변경 API
- 채팅방 멤버 조회 API
- 채팅방 멤버 초대 API
검증 로직이 빠진 부분이 있는지 체크해주시면 좋을 것 같아요
<br/>
---
> Feat/#69: 채팅방 수정 api

- build.gradle
- src/main/java/space/space_spring/config/WebConfig.java
- src/main/java/space/space_spring/dao/UserDao.java
- src/main/java/space/space_spring/service/UserService.java
- src/main/java/space/space_spring/util/user/UserUtils.java
이슈 번호 : #89 
1. p6spy 설정 제거 -> 이제 로그가 좀 더 꺠끗해질것입니다
2. 유저 이메일로 유저 엔티티 찾아오는 코드에 유저의 회원가입 타입을 이용한 로직 추가
-> 로컬 회원가입, 소셜 회원가입으로 가입한 유저의 이메일을 구분하여 이메일 엔티티를 찾아옵니다
3. webConfig의 exposedHeaders 속성에 Authorization 추가 -> response header의 jwt를 프론트에서 사용할 수 있습니다
<br/>
---
> Refactor/#89/개발한 api 전체 점검

- src/main/java/space/space_spring/controller/VoiceRoomController.java
- src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java
- src/main/java/space/space_spring/service/S3Uploader.java
- resolved #104 
http status code 수정 및 추가
<br/>
---
> Refactor/#104: httpstatus 에러 코드 수정

- src/main/java/space/space_spring/controller/SpaceController.java
- src/main/java/space/space_spring/dto/chat/response/ChatRoomResponse.java
- src/main/java/space/space_spring/service/ChatRoomService.java
> 24.08.16 3차 배포 

- src/main/java/space/space_spring/dto/pay/dto/TotalPayInfoDto.java
- src/main/java/space/space_spring/dto/space/GetSpaceJoinDto.java
- src/main/java/space/space_spring/service/PayService.java
- src/main/java/space/space_spring/service/SpaceService.java
정산 상세정보 조회 api 의 response에 해당 정산 생성일의 정보를 추가했습니다
이슈 번호 : #121 
<br/>
---
> HotFix : 정산 상제조회 api response에 생성일 정보 추가

- src/main/java/space/space_spring/entity/BaseEntity.java
- src/main/java/space/space_spring/service/ChatRoomService.java
- UTC+9 타임존 set 버그 수정
- 이미 나가기(INACTIVE)인 유저가 재초대될 경우 로직 추가
<br/>
---
> Hotfix: 타임존 및 유저 초대 버그 수정

- src/main/java/space/space_spring/controller/ImageS3Controller.java
- src/main/java/space/space_spring/service/S3Uploader.java
- 이슈 번호 : #134 
S3 파일 이름 / URL 이름에 고유 식별자 (UUID) 부여
`S3Uploader`에 있는 `upload` 메소드를 수정하였습니다.
이제 모든 파일이 파일 이름과 관계 없이 식별자를 통해 업로드 됩니다.
기존에 사진 업로드를 사용하는 기능들 잘 동작하는지 확인 한번씩 부탁드립니다.
<br/>
---
> Feat/#134/image UUID 적용

- src/main/java/space/space_spring/controller/OAuthController.java
> fix : 카카오로그인 response redirect

- build.gradle
- src/main/java/space/space_spring/controller/PostController.java
- src/main/java/space/space_spring/domain/pay/controller/PayController.java
- src/main/java/space/space_spring/domain/pay/model/EqualSplitPayAmountPolicy.java
- src/main/java/space/space_spring/domain/pay/model/IndividualPayAmountPolicy.java
- src/main/java/space/space_spring/domain/pay/model/Money.java
- src/main/java/space/space_spring/domain/pay/model/PayAmountPolicy.java
- src/main/java/space/space_spring/domain/pay/model/PayCreateTargetInfo.java
- src/main/java/space/space_spring/domain/pay/model/PayCreateValidator.java
- src/main/java/space/space_spring/domain/pay/model/PayType.java
- src/main/java/space/space_spring/domain/pay/model/entity/PayRequest.java
- src/main/java/space/space_spring/domain/pay/model/request/PayCreateRequest.java
- src/main/java/space/space_spring/domain/pay/model/request/PayCreateServiceRequest.java
- src/main/java/space/space_spring/domain/pay/model/request/PayCreateTargetInfo.java
- src/main/java/space/space_spring/domain/pay/model/request/TargetInfoRequest.java
- src/main/java/space/space_spring/domain/pay/repository/PayDao.java
- src/main/java/space/space_spring/domain/pay/repository/PayRequestRepository.java
- src/main/java/space/space_spring/domain/pay/service/PayService.java
- src/main/java/space/space_spring/global/common/EnumValidator.java
- src/main/java/space/space_spring/global/common/EnumValidatorConstraint.java
- src/main/java/space/space_spring/response/status/BaseExceptionResponseStatus.java
- src/test/java/space/space_spring/domain/pay/controller/PayControllerTest.java
- src/test/java/space/space_spring/domain/pay/model/EqualSplitPayAmountPolicyTest.java
- src/test/java/space/space_spring/domain/pay/model/IndividualPayAmountPolicyTest.java
- src/test/java/space/space_spring/domain/pay/model/PayCreateValidatorTest.java
- src/test/java/space/space_spring/domain/pay/model/entity/PayRequestTest.java
- src/test/java/space/space_spring/domain/pay/model/firstCollection/PayRequestTargetsTest.java
- src/test/java/space/space_spring/domain/pay/model/firstCollection/PayRequestsTest.java
- src/test/java/space/space_spring/domain/pay/service/PayServiceTest.java
> Refactor/#172/정산 생성 api

- src/main/java/space/space_spring/domain/spaceMember/SpaceMember.java
- src/main/java/space/space_spring/domain/spaceMember/SpaceMemberJpaEntity.java
- src/main/java/space/space_spring/domain/spaceMember/SpaceMemberMapper.java
- src/test/java/space/space_spring/domain/pay/application/service/CreatePayServiceTest.java
이슈 번호 : #187 
erd Space_Member 테이블 컬럼 추가, SpaceMember jpa 엔티티 필드 추가 & @NotNull 어노테이션 및 @Column 어노테이션 추가, SpaceMember 도메인 엔티티 필드 추가
<br/>
---
> Hotfix/#187/spacemember 도메인 엔티티 수정

- src/main/java/space/space_spring/domain/post/adapter/in/web/BoardController.java
- src/main/java/space/space_spring/domain/post/adapter/in/web/RequestOfCreateBoard.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/BoardJpaEntity.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/BoardMapper.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/BoardPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/SpringDataBoardRepository.java
- src/main/java/space/space_spring/domain/post/application/port/in/CreateBoard/CreateBoardCommand.java
- src/main/java/space/space_spring/domain/post/application/port/in/CreateBoard/CreateBoardUseCase.java
- src/main/java/space/space_spring/domain/post/application/port/out/CreateBoardPort.java
- src/main/java/space/space_spring/domain/post/application/service/CreateBoardService.java
- src/main/java/space/space_spring/domain/post/domain/Attachment.java
- src/main/java/space/space_spring/domain/post/domain/AttachmentType.java
- src/main/java/space/space_spring/domain/post/domain/Board.java
- src/main/java/space/space_spring/domain/post/domain/BoardType.java
- src/main/java/space/space_spring/domain/post/domain/Comment.java
- src/main/java/space/space_spring/domain/post/domain/Like.java
- src/main/java/space/space_spring/domain/post/domain/Post.java
- src/main/java/space/space_spring/domain/post/domain/PostBase.java
- src/main/java/space/space_spring/domain/post/domain/Question.java
- src/main/java/space/space_spring/global/common/response/status/BaseExceptionResponseStatus.java
이슈 번호 : #184 
먼저, 도메인 엔티티는 게시판을 위주로 수정하고 게시판 생성 api를 추가해보았습니다.
리뷰를 받은 후 개선한 다음 게시글 생성 api를 개발하면 좋을 것 같아서 먼저 pr 올렸습니다. 
조언 주시면 감사하겠습니다!
<br/>
---
> Feat/#184/게시판 생성

- src/main/java/space/space_spring/domain/post/adapter/out/persistence/like/LikeJpaEntity.java
> Hotfix : LikeJpaEntity 테이블명 수정

- docker-compose.yml
> fix : docker compose

- src/main/java/space/space_spring/domain/discord/adapter/in/discord/TestTextCommandEventListener.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/like/LikeJpaEntity.java
- src/main/java/space/space_spring/global/config/JDA/JDAConfig.java
- src/main/java/space/space_spring/global/config/JDA/SlashCommandRegistrar.java
- 이슈 번호 : #216
1. 텍스트 명령어 prod 버전 제한
2. 봇 설명란에 현재 project 버전 표시 ("local" / "dev")
3. discord slash 명령어 권한 추가
<br/>
---
> Feat/#216/데모데이 배포용 discord 명령어 권한 추가

- .github/workflows/gradle-dev.yml
- docker-compose.yml
이슈 번호 : #223 
docker-compose.yml 파일로 build 진행되도록 수정했습니다
<br/>
---
> fix : gradle_dev.yml

- .github/workflows/gradle-dev.yml
이슈 번호 : #226 
1. gradle-dev.yml 의 build-and-deploy-docker 에서 
dockerfile 을 못찾는 이슈 발생
-> - uses: actions/checkout@v4 추가 
-> 리포지토리 체크아웃 하는 코드 추가
2. dockerfile 내부에 build 를 위한 코드 포함되어 있다
-> gradle-dev.yml 의 build-and-deploy-docker 에도 프로젝트 build를 위한 코드 추가
<br/>
---
> Fix/#226/gradle devyml 수정

- .github/workflows/gradle-dev.yml
- docker-compose.yml
이슈 번호 : #226 
gradle-dev.yml 에서 깃허브 시크릿 레포지토리에 주입한 application-dev.yml 을 프로젝트의 application.yml 로 교체해서 build 하는 코드를 수정했습니다
기존에는 프로젝트에 존재하는 application.yml 코드의 아래줄에 application-dev.yml 내용을 추가하기만해서 에러가 발생한 것이었습니다.
추가로 RDS 새로 설정한 후, datasource 정보 업데이트한 새로운 application-dev.yml 을 깃헙 시크릿 레포지토리에 추가했습니다.
아직 RDS와 연동해서 api 요청을 처리하는 것은 테스트해보진 못했습니다. 머지후에 RDS와 연동해서 CRUD 테스트해보면 될거 같습니다.
<br/>
---
> fix : gradle-yml, application-dev.yml 의존성 주입 코드 수정

- .github/workflows/gradle-dev.yml
- docker-compose.yml
docker dev server 배포 파일 수정 
<br/>
---
> fix : deploy 재 배포 

- src/main/java/space/space_spring/domain/user/adapter/out/persistence/DiscordOauthAdapter.java
> Hotfix/oauth debugging

- src/main/java/space/space_spring/domain/post/adapter/out/persistence/attachment/AttachmentPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/attachment/SpringDataAttachmentRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/PostPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/SpringDataPostRepository.java
- src/main/java/space/space_spring/domain/spaceMember/adapter/out/persistence/SpaceMemberPersistenceAdapter.java
- src/main/java/space/space_spring/domain/spaceMember/adapter/out/persistence/SpringDataSpaceMemberRepository.java
이슈 번호 : #252 
게시글 리스트 조회 시, 쿼리 enum 패키지 경로 제거
<br/>
---
> fix: repository 쿼리 enum 수정

- src/main/java/space/space_spring/domain/user/adapter/in/web/TokenController.java
> Hotfix: pathvariable 추가

- src/main/java/space/space_spring/domain/pay/adapter/in/web/completePay/CompletePayController.java
- src/main/java/space/space_spring/domain/pay/adapter/in/web/createPay/CreatePayController.java
- src/main/java/space/space_spring/domain/pay/adapter/in/web/deletePay/DeletePayController.java
- src/main/java/space/space_spring/domain/pay/adapter/in/web/readBankInfo/ReadBankInfoController.java
- src/main/java/space/space_spring/domain/pay/adapter/in/web/readPayDetail/ReadSinglePayController.java
- src/main/java/space/space_spring/domain/pay/adapter/in/web/readPayHome/ReadPayHomeController.java
- src/main/java/space/space_spring/domain/pay/adapter/in/web/readPayRequestList/ReadPayRequestListController.java
- src/main/java/space/space_spring/domain/pay/adapter/in/web/readRequestedPayList/ReadRequestedPayListController.java
정산 관련 api의 controller에 pathvariable spaceId가 없어, 스웨거 상으로 spaceId를 입력받기 제한되는 이슈 발생
-> controller에 pathvariable spaceId 추가
이슈 번호 : #299 
<br/>
---
> fix : 정산 관련 api에 spaceId pathvariable 추가

- src/main/java/space/space_spring/domain/discord/application/service/CreatePayInDiscordService.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/board/BoardPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/board/SpringDataBoardRepository.java
- src/main/java/space/space_spring/domain/post/application/port/in/loadBoard/LoadBoardUseCase.java
- src/main/java/space/space_spring/domain/post/application/port/out/LoadBoardPort.java
- src/main/java/space/space_spring/domain/post/application/service/LoadBoardService.java
정산 디스코드 생성에서 기존에 없던 정산 채널 입력 코드
- 이슈 번호 : #305 
<br/>
---
> Hotfix : 정산 디스코드 생성 과정에서 정산 채널 입력

- src/main/java/space/space_spring/domain/discord/application/port/out/CreateDiscordWebHookMessageCommand.java
첨부파일이 없을때 null pointer error가 발생하는 코드를 수정하였습니다
- 이슈 번호 : #311
<br/>
---
> fit : add attachment null

- src/main/java/space/space_spring/domain/event/adapter/in/web/createEvent/CreateEventController.java
- src/main/java/space/space_spring/domain/event/adapter/in/web/createEvent/CreateEventRequest.java
> Hotfix/#313: formdata 설정 추가

- src/main/java/space/space_spring/domain/post/adapter/in/web/subscribeBoard/SubscribeBoardController.java
- src/main/java/space/space_spring/domain/post/adapter/in/web/subscribeBoard/SubscribeBoardRequest.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/SubscriptionPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/SubscriptionRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/tag/SpringDataTagRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/tag/TagPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/application/port/in/loadBoard/SubscribeBoardCommand.java
- src/main/java/space/space_spring/domain/post/application/port/out/LoadSubscriptionPort.java
- src/main/java/space/space_spring/domain/post/application/port/out/LoadTagPort.java
- src/main/java/space/space_spring/domain/post/application/service/SubscribeBoardService.java
- src/main/java/space/space_spring/domain/post/domain/Subscription.java
- resolved #315 
- 구독 요청 / 취소 요청 시 태그가 null이 될 수 있음에 따라 분기 처리 추가
<br/>
---
> Fix/#315: tag 속성 변경에 따른 구독 로직 수정

- src/main/java/space/space_spring/domain/discord/application/port/in/createPost/CreatePostInDiscordCommand.java
- src/main/java/space/space_spring/domain/discord/application/port/out/CreateDiscordWebHookMessageCommand.java
- src/main/java/space/space_spring/domain/discord/application/service/CreatePostInDiscordService.java
- src/main/java/space/space_spring/domain/post/application/port/in/createPost/CreatePostCommand.java
- src/main/java/space/space_spring/domain/post/application/service/CreatePostService.java
> fix: 게시글 익명 여부에 따른 사용자 정보 전달

- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CreateChannel/CreateBoardButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/TestTextCommandEventListener.java
- src/main/java/space/space_spring/domain/discord/adapter/out/DiscordWebHookAdapter.java
- src/main/java/space/space_spring/domain/discord/application/port/out/CreateDiscordWebHookMessageCommand.java
- src/main/java/space/space_spring/domain/discord/application/port/out/WebHookPort.java
webHook 관리 통일 
- 이슈 번호 : #271
- `WebHookAdapter`
- attachment null 에러 수정 
<br/>
---
> Feat : "Space_Member" webHook을 관리하는 WebHookAdapter

- src/main/java/space/space_spring/domain/discord/application/port/out/CreateDiscordThreadCommand.java
- src/main/java/space/space_spring/domain/discord/domain/DiscordPayMessage.java
- src/test/java/space/space_spring/domain/discord/PayMessageGenerate.java
디스코드 상에서 보이는 Pay message 수정 
+ 금액 정렬 코드 추가
- 이슈 번호 : #326 
- 디스코드에서 돈이 제대로 출력 되지 않는 사항을 수정했습니다. 추후 `Money`에 출력 책임 리팩토링 하면 좋을 것 같습니다
- 디스코드에서 null이 한줄 출력 되는 오류 수정 -> 아직 확인 못해봄
- 디스코드에서 금액이 보이는 방식을 수정 했습니다 . 각 금액 별로 정리해서 보여줍니다.
- 관련 test 코드 추가했습니다. 출력 되어 눈으로 확인 가능합니다. ( validation하지 않음)
<br/>
---
> Feat : Pay discord 출력 수정

- src/main/java/space/space_spring/global/config/WebConfig.java
> Fix/#337: Refresh Token 접근을 위한 CORS 설정 추가

- src/main/java/space/space_spring/domain/discord/application/port/in/updatePost/UpdatePostInDiscordCommand.java
- src/main/java/space/space_spring/domain/post/adapter/in/web/createPost/RequestOfCreatePost.java
- src/main/java/space/space_spring/domain/post/adapter/in/web/updatePost/RequestOfUpdatePost.java
- src/main/java/space/space_spring/domain/post/adapter/in/web/updatePost/UpdatePostController.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/attachment/SpringDataAttachmentRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/postTag/PostTagPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/postTag/SpringDataPostTagRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/tag/SpringDataTagRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/tag/TagPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/application/port/in/updatePost/UpdatePostCommand.java
- src/main/java/space/space_spring/domain/post/application/port/in/updatePost/UpdatePostFromDiscordCommand.java
- src/main/java/space/space_spring/domain/post/application/port/out/LoadTagPort.java
- src/main/java/space/space_spring/domain/post/application/port/out/UpdatePostTagPort.java
- src/main/java/space/space_spring/domain/post/application/service/CreatePostService.java
- src/main/java/space/space_spring/domain/post/application/service/UpdatePostService.java
게시글 수정시 첨부파일과 tag 정보들을 추가하였습니다.
이슈 번호 : #333
<br/>
---
> Feat/#333/게시글댓글 수정 삭제 from 디스코드

- src/main/java/space/space_spring/domain/event/application/service/ReadEventParticipantService.java
- src/main/java/space/space_spring/domain/event/application/service/ReadEventService.java
이슈 번호 : #번호
행사 조회 시 관리자 권한 해제
<br/>
---
> Hotfix: event auth setting

- src/test/java/space/space_spring/domain/event/application/service/ReadEventParticipantServiceTest.java
> Fix: build error

- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CreateChannel/MoveMessageButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/DiscordMessageMapper.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/MessageCreateEventListener.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/TestTextCommandEventListener.java
- src/main/java/space/space_spring/domain/discord/adapter/out/discord/DiscordForumRepository.java
- src/main/java/space/space_spring/domain/discord/application/port/in/discord/MessageInputFromDiscordCommand.java
- src/main/java/space/space_spring/domain/discord/application/port/out/CreateDiscordWebHookMessageCommand.java
- src/main/java/space/space_spring/domain/discord/application/service/MessageInputFromDiscordService.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/tag/SpringDataTagRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/tag/TagPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/application/port/in/Tag/LoadTagUseCase.java
- src/main/java/space/space_spring/domain/post/application/port/in/createPost/CreatePostFromDiscordCommand.java
- src/main/java/space/space_spring/domain/post/application/port/in/createPost/CreatePostUseCase.java
- src/main/java/space/space_spring/domain/post/application/port/out/LoadTagPort.java
- src/main/java/space/space_spring/domain/post/application/service/CreatePostService.java
- src/main/java/space/space_spring/domain/post/application/service/TagService.java
게시물에 tag를 붙여주는 코드 입니다
+attachmentType도 붙여줍니다.
- 이슈 번호 : #341
<br/>
---
> Feat : discord/server에서 생성된 post에 tag 설정 + attachmentType

- src/main/java/space/space_spring/domain/discord/adapter/in/discord/DiscordMessageMapper.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/MessageUpdateEventListener.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/TestTextCommandEventListener.java
- src/main/java/space/space_spring/domain/discord/adapter/out/EditDiscordMessage/EditDiscordMessageAdapter.java
- src/main/java/space/space_spring/domain/discord/application/port/in/updateComment/UpdateCommentInDiscordCommand.java
- src/main/java/space/space_spring/domain/discord/application/port/in/updatePost/UpdatePostInDiscordCommand.java
- src/main/java/space/space_spring/domain/discord/application/port/out/updateMessage/UpdateMessageInDiscordPort.java
- src/main/java/space/space_spring/domain/discord/application/service/UpdateCommentInDiscordService.java
- src/main/java/space/space_spring/domain/discord/application/service/UpdatePostInDiscordService.java
- src/main/java/space/space_spring/domain/post/application/port/in/updatePost/UpdatePostFromDiscordCommand.java
- src/main/java/space/space_spring/domain/post/application/port/in/updatePost/UpdatePostUseCase.java
- src/main/java/space/space_spring/domain/post/application/service/UpdateCommentService.java
- src/main/java/space/space_spring/domain/post/application/service/UpdatePostService.java
댓글 / 게시물 수정 port
- 이슈 번호 : #288
- command에 webhook을 추가했습니다
<br/>
---
> Feat : 댓글 / 게시물 수정 port

- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CreateChannel/CategoryButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CreateChannel/CheckBoardCreateButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CreateChannel/CheckDeleteChannelButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CreateChannel/CreateBoardButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CreateChannel/CreateChannelButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CreateChannel/DeleteChannelButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ChannelSettingEventListener.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/RoleEventListener.java
- src/main/java/space/space_spring/domain/space/adapter/out/persistence/SpacePersistenceAdapter.java
- src/main/java/space/space_spring/domain/space/adapter/out/persistence/SpringDataSpace.java
- src/main/java/space/space_spring/domain/spaceMember/adapter/out/persistence/SpaceMemberPersistenceAdapter.java
- src/main/java/space/space_spring/domain/spaceMember/adapter/out/persistence/SpringDataSpaceMemberRepository.java
- src/main/java/space/space_spring/domain/spaceMember/application/port/in/UpdateSpaceMemberUseCase.java
- src/main/java/space/space_spring/domain/spaceMember/application/port/out/UpdateSpaceMemberPort.java
- src/main/java/space/space_spring/domain/spaceMember/application/service/UpdateSpaceMemberService.java
디스코드 부족한 부분 기능 추가
- 채널이 25개 이상 될 경우, 한번의 메세지 버튼으로 출력 불가능
- 중간에 채널 카테고리를 고르는 버튼 과정을 추가 함으로써 버튼 개수 축소
- `SpaceMamber` role 을 디스코드에서 추가 시 `isManager` 추가  
- 이슈 번호 : #354 
<br/>
---
> Fix : 게시판 생성 버튼 플로우 수정(category 추가) & spaceManager role 수정 시 반영 

- src/main/java/space/space_spring/domain/home/adapter/in/web/NoticeSummary.java
- src/main/java/space/space_spring/domain/home/adapter/in/web/ReadHomeController.java
- src/main/java/space/space_spring/domain/home/adapter/in/web/ReadHomeResponse.java
- src/main/java/space/space_spring/domain/home/adapter/in/web/ReadHomeResult.java
- src/main/java/space/space_spring/domain/home/adapter/in/web/SubscriptionSummary.java
- src/main/java/space/space_spring/domain/home/application/port/in/ReadHomeUseCase.java
- src/main/java/space/space_spring/domain/home/application/service/ReadHomeService.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/PostPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/SpringDataPostRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/custom/PostRepositoryCustom.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/custom/PostRepositoryImpl.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/SubscriptionPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/SubscriptionRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/tag/SpringDataTagRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/tag/TagPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/application/port/out/LoadPostPort.java
- src/main/java/space/space_spring/domain/post/application/port/out/LoadSubscriptionPort.java
- src/main/java/space/space_spring/domain/post/application/port/out/LoadTagPort.java
- src/main/java/space/space_spring/global/common/response/status/BaseExceptionResponseStatus.java
- resolved #292
- 홈 조회 API 개발
<br/>
---
> Feat/#292: 스페이스 홈 조회 api

- src/main/java/space/space_spring/domain/post/adapter/out/persistence/attachment/AttachmentPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/comment/CommentPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/PostPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/PostRepository.java
`SpringData` prefix 제거함으로써 커스텀 레포지토리 사용 가능
<br/>
---
> Hotfix: jpa 설정 prefix 제거

- src/main/java/space/space_spring/domain/home/application/service/ReadHomeService.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/PostPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/custom/PostRepositoryCustom.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/post/custom/PostRepositoryImpl.java
- src/main/java/space/space_spring/domain/post/application/port/out/LoadPostPort.java
- resolved #375 
홈의 구독한 게시판 조회 로직을 기획에 맞게 수정
- 기획 : 각 구독한 게시판의 가장 최신 글 제목을 보여줌
개발되어있던 로직 : 각 구독한 게시판의 모든 글의 제목을 보여줌
<br/>
---
> Fix/#375: 홈 조회 버그 수정

- src/main/java/space/space_spring/domain/event/adapter/out/persistence/EventParticipantPersistenceAdapter.java
- src/main/java/space/space_spring/domain/event/adapter/out/persistence/EventParticipantRepository.java
- resolved #365 
행사 참여자 조회 시 createdAt 기준으로 최신순 정렬
<br/>
---
> Feat/#365: 행사 참여자 조회 시 최신순으로 조회

- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/CancelButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/PayComplete/CheckPayCompleteButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/ButtonInteraction/PayComplete/PayCompleteButtonProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/out/PayInDiscord/PayCompleteButtonInDiscord.java
- src/main/java/space/space_spring/domain/discord/adapter/out/discord/DiscordThreadRepository.java
- src/main/java/space/space_spring/domain/discord/application/port/out/Pay/CreatePayCompleteButtonPort.java
- src/main/java/space/space_spring/domain/discord/application/service/CreatePayInDiscordService.java
- src/main/java/space/space_spring/domain/discord/application/service/MessageInputFromDiscordService.java
- src/main/java/space/space_spring/domain/pay/adapter/out/persistence/PayRequestPersistenceAdapter.java
- src/main/java/space/space_spring/domain/pay/adapter/out/persistence/SpringDataPayRequestRepository.java
- src/main/java/space/space_spring/domain/pay/application/port/in/validatePayTarget/ValidatePayTargetUseCase.java
- src/main/java/space/space_spring/domain/pay/application/port/out/LoadPayRequestPort.java
- src/main/java/space/space_spring/domain/pay/application/service/ValidatePatTargetService.java
정산 완료를 확인하는 버튼을 정산 thread에 추가합니다.
- 이슈 번호 : #366
아직 테스트 해보지 못했습니다
@seongjunnoh 혹시 가능하시다면 정산 생성과 연동해서 확인 부탁드립니다
<br/>
---
> Feat : 정산 완료 버튼 discord 출력

- src/main/java/space/space_spring/domain/discord/adapter/in/discord/MessageCreate/MessageInputProcessor/TextPostMessageInputProcessor.java
- src/main/java/space/space_spring/domain/discord/adapter/in/discord/MessageReactionEventListener.java
- src/main/java/space/space_spring/domain/discord/application/service/MessageInputFromDiscordService.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/board/BoardPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/board/SpringDataBoardRepository.java
- src/main/java/space/space_spring/domain/post/application/port/out/DeleteBoardPort.java
- src/main/java/space/space_spring/domain/post/application/service/DeleteBoardService.java
- src/main/java/space/space_spring/domain/space/adapter/out/persistence/SpringDataSpace.java
- 이슈 번호 : #383
board 삭제 과정 추가
이모지 오류 수정
<br/>
---
> Hotfix : board delete / emoji delete

- src/main/java/space/space_spring/domain/discord/adapter/out/discord/DiscordForumRepository.java
resolved : #385 
JDA로 보내는 코드 뒤쪽에 .queue() 달았습니다
<br/>
---
> fix : 태그 정보 JDA로 보내도록 수정

- src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/SubscriptionMapper.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/SubscriptionPersistenceAdapter.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/SubscriptionRepository.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/custom/SubscriptionRepositoryCustom.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/subscription/custom/SubscriptionRepositoryImpl.java
- src/main/java/space/space_spring/domain/post/application/service/SubscribeBoardService.java
- resolved #309 
- 게시판 구독 시 태그 없는 경우에 대한 예외 처리 추가
- 게시판 조회 시 구독 여부 조회 버그 수정
<br/>
---
> Fix/#309: 구독 버그 수정

- src/main/java/space/space_spring/domain/post/adapter/out/persistence/postBase/PostBaseJpaEntity.java
- 이슈 번호 : #390 
@Column(columnDefinition = "LONGTEXT")
추가
<br/>
---
> [fix] postBase content 크기 제한 해결

- build.gradle
> Hotfix: add-sql-log

- src/main/java/space/space_spring/domain/discord/adapter/in/discord/MessageCreate/MessageInputProcessor/CommentMessageInputProcessor.java
- src/main/java/space/space_spring/domain/discord/application/port/in/discord/InputMessageFromDiscordUseCase.java
- src/main/java/space/space_spring/domain/discord/application/service/MessageInputFromDiscordService.java
- 이슈 번호 : #390 
Comment 생성 시 post id가 잘못 입력되는 코드 수정 
<br/>
---
> [fix] comment create parameter fix

- src/main/java/space/space_spring/domain/discord/adapter/in/discord/TestTextCommandEventListener.java
- src/main/java/space/space_spring/domain/discord/application/port/out/CreateDiscordWebHookMessageCommand.java
- src/main/java/space/space_spring/domain/discord/application/service/CreatePostInDiscordService.java
- src/main/java/space/space_spring/domain/post/application/service/TagService.java
- 이슈 번호 : #396 
tagid가 discord에서 discordId로 변환되지 않던 오류를 수정했습니다
<br/>
---
> [fix] tagId와 tagDiscordId 구분

- src/main/java/space/space_spring/domain/post/adapter/in/web/readPostDetail/ResponseOfCommentDetail.java
- src/main/java/space/space_spring/domain/post/adapter/out/persistence/comment/CommentQueryAdapter.java
- src/main/java/space/space_spring/domain/post/application/port/in/readPostDetail/InfoOfCommentDetail.java
- src/main/java/space/space_spring/domain/post/application/port/out/comment/CommentDetailView.java
- src/main/java/space/space_spring/domain/post/application/service/ReadPostDetailService.java
- src/main/java/space/space_spring/domain/post/application/service/strategy/AnonymousCommentProcessingStrategy.java
- src/main/java/space/space_spring/domain/post/application/service/strategy/InactiveCommentProcessingStrategy.java
resolved : #410 
- 프론트 분들의 요청으로 게시글 상세 조회 api 의 response에 commentId 추가
- 이에 따른 코드 수정
로컬 서버에서 테스트 한 결과 입니다
<br/>
---
> Refactor/#410/게시글 상세 조회 api

- src/main/java/space/space_spring/domain/event/adapter/in/web/createEvent/CreateEventController.java
- src/main/java/space/space_spring/domain/event/adapter/in/web/readEvent/EventInfoResponse.java
- src/main/java/space/space_spring/domain/event/adapter/in/web/readEvent/ReadEventInfoResponse.java
- src/main/java/space/space_spring/domain/event/application/service/JoinEventService.java
- src/main/java/space/space_spring/domain/event/application/service/ModifyEventService.java
- src/main/java/space/space_spring/global/common/response/status/BaseExceptionResponseStatus.java
- src/main/java/space/space_spring/global/util/TimeConverter.java
- src/test/java/space/space_spring/domain/event/application/service/JoinEventServiceTest.java
- resolved #378 
- 행사 생성 시 시간 포맷이 맞지 않는 경우에 대해 커스텀 에러 적용
- 행사 생성 시 시작 시간과 종료 시간에 대한 validation 추가
- 행사 진행 시간이 아닐 때에 들어온 행사 참여 요청에 대한 validation 추가
- 행사 날짜가 행사 시작 날짜와 동일한 날짜가 아닌 경우에 대한 validation 추가
- 시간 포맷이 맞지 않는 경우
- 시작 시간이 종료 시간보다 이후인 경우
- 유저가 직접 행사 참여 또는 관리자가 참여자 추가 시 행사 진행 시간이 아닌 경우
- 행사 날짜와 행사 시작 날짜가 다른 경우
<br/>
---
> Refactor/#378: 행사 생성 시 커스텀 에러 적용

- src/main/java/space/space_spring/domain/home/adapter/in/web/NoticeSummary.java
- src/main/java/space/space_spring/domain/home/application/service/ReadHomeService.java
resolved : #419 
석준님의 요청으로 스페이스 홈 조회 api의 response 중 notices에 공지사항의 postId 값을 추가하였습니다
<br/>
---
> refactor : 공지사항의 id값 추가

- src/main/java/space/space_spring/domain/event/application/service/ModifyEventService.java
- resolved #424 
- 관리자가 행사 참여자를 추가/삭제할 때에는 행사 진행 시간인지 여부를 확인하지 않음
<br/>
---
> Feat: 행사 참여자 수정 시 날짜 제한 해제

- src/main/java/space/space_spring/domain/space/application/service/CreateSpaceService.java
- 이슈 번호 : #429 
버튼 취소 버그 수정
<br/>
---
> [feat] 버튼 취소 처리 
